-- Requète 1
SELECT IDN, PROFONDEUR, SEUIL
FROM IA_NEURONNE
WHERE IDR = 1
ORDER BY PROFONDEUR;

-- Requète 2
SELECT R.IDR, R.FONCTION
FROM IA_RESEAU R
INNER JOIN (
    SELECT IDR, COUNT(DISTINCT IDN_I || IDN_O) NB
    FROM IA_CONNECTER
    INNER JOIN IA_NEURONNE ON IDN = IDN_I OR IDN = IDN_O
    GROUP BY IDR) TMP ON TMP.IDR = R.IDR
WHERE ROWNUM = 1
ORDER BY TMP.NB DESC;

-- Requète 3
SELECT C.IDR, C.PROFONDEUR, COUNT(IDN) AS "Nb_Neuronne"
FROM IA_COUCHE C
INNER JOIN IA_NEURONNE N ON C.IDR = N.IDR AND C.PROFONDEUR = N.PROFONDEUR
GROUP BY C.IDR, C.PROFONDEUR
ORDER BY C.IDR, C.PROFONDEUR;

-- Requète 4
SELECT * FROM (
    SELECT IDN, COUNT(Ci.IDN_O) + COUNT(Co.IDN_I) as NB
    FROM IA_NEURONNE N
    LEFT OUTER JOIN IA_CONNECTER Ci ON N.IDN = Ci.IDN_I
    LEFT OUTER JOIN IA_CONNECTER Co ON N.IDN = Co.IDN_O
    GROUP BY IDN
    ORDER BY NB DESC) TMP
WHERE ROWNUM <= 5;
