CREATE TABLE ia_reseau
(
  idR NUMBER(4),
  fonction VARCHAR(10),
  CONSTRAINT pk_reseau PRIMARY KEY (idR)
);

CREATE TABLE ia_couche
(
  profondeur NUMBER(5),
  idR NUMBER(4),
  CONSTRAINT pk_couche PRIMARY KEY (idR, profondeur),
  CONSTRAINT fk_couche FOREIGN KEY (idR) REFERENCES ia_reseau(idR)
);

CREATE TABLE ia_neuronne
(
  idN NUMBER(4),
  seuil NUMBER(5),
  idR NUMBER(4),
  profondeur NUMBER(5),
  CONSTRAINT pk_neuronne PRIMARY KEY (idN),
  CONSTRAINT fk_neuronne_pro FOREIGN KEY (idR, profondeur) REFERENCES ia_couche(idR, profondeur)
);

CREATE TABLE ia_connecter
(
  idN_I NUMBER(4),
  idN_O NUMBER(4),
  poids VARCHAR(5),
  CONSTRAINT pk_neuronne_con PRIMARY KEY (idN_I, idN_O),
  CONSTRAINT fk_neuronne_I FOREIGN KEY (idN_I) REFERENCES ia_neuronne(idN),
  CONSTRAINT fk_neuronne_O FOREIGN KEY (idN_O) REFERENCES ia_neuronne(idN)
);

INSERT ALL
    INTO IA_RESEAU (IDR, FONCTION) VALUES (0, 'RA')
    INTO IA_RESEAU (IDR, FONCTION) VALUES (1, 'RB')
    INTO IA_COUCHE (PROFONDEUR, IDR) VALUES (0, 0)
    INTO IA_COUCHE (PROFONDEUR, IDR) VALUES (1, 0)
    INTO IA_COUCHE (PROFONDEUR, IDR) VALUES (2, 0)
    INTO IA_COUCHE (PROFONDEUR, IDR) VALUES (0, 1)
    INTO IA_COUCHE (PROFONDEUR, IDR) VALUES (1, 1)
    INTO IA_COUCHE (PROFONDEUR, IDR) VALUES (2, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (0, 1, 0, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (1, 2, 0, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (2, 3, 0, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (3, 4, 1, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (4, 5, 1, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (5, 6, 1, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (6, 7, 2, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (7, 8, 2, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (8, 9, 2, 0)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (9, 10, 0, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (10, 11, 0, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (11, 12, 0, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (12, 13, 1, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (13, 14, 1, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (14, 15, 1, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (15, 16, 2, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (16, 17, 2, 1)
    INTO IA_NEURONNE (IDN, SEUIL, PROFONDEUR, IDR) VALUES (17, 18, 2, 1)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (3,4, 42)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (2,9, 32)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (12,6, 51)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (17,14, 12)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (16,1, 82)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (15,7, 23)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (5,8, 43)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (9,2, 24)
    INTO IA_CONNECTER (IDN_I, IDN_O, POIDS) VALUES (14,2, 25)
SELECT * FROM dual;
