

SELECT R.IDR, R.FONCTION
FROM IA_RESEAU R
INNER JOIN (
    SELECT IDR, COUNT(DISTINCT IDN_I || IDN_O) NB
    FROM IA_CONNECTER
    INNER JOIN IA_NEURONNE ON IDN = IDN_I OR IDN = IDN_O
    GROUP BY IDR) TMP ON TMP.IDR = R.IDR
WHERE ROWNUM = 1
ORDER BY TMP.NB DESC;
